### ISSUE TITLE
Advice on Modifying html2text Behavior to Preserve Link Text

### ISSUE THREAD

**Issue by devstein** [k3a/html2text#15]
Hi 👋

Thanks for making and maintaining this package! It's almost exactly what I was looking for. The only different behavior I am looking for is to preserve the link text and append the link as a suffix to the text in the conversion.

For example, the behavior I want is
```go
So(HTML2Text(`click <a href="javascript:void(0)">here</a>`), ShouldEqual, "click here")
So(HTML2Text(`click <a href="test"><span>here</span> or here</a>`), ShouldEqual, "click test <test>")
So(HTML2Text(`click <a href="http://bit.ly/2n4wXRs">news</a>`), ShouldEqual, "click news <http://bit.ly/2n4wXRs>")
```

I understand a change like would be breaking for users and change the interface, so I am planning on forking the repo to make this change. 

Do you have advice on how to make this change? It's clear that changes would need to be made [here](https://github.com/k3a/html2text/blob/master/html2text.go#L203-L217). Any advice is appreciated!

**Comment by devstein** [comment]
Took a stab at it 😁  [PR is here](https://github.com/devstein/html2text/pull/1/files)

@k3a The only part I'm unsure of is [this line](https://github.com/devstein/html2text/pull/1/files#diff-77078dd610ab6e8b5ebaa0bf46883c3a949b7b26ec0bbed905f32c8564772776R204). 

Do I need to also look for `tagNameLowercase == "a"` or will the closing tag always be `tagNameLowercase == "/a"`

**Comment by k3a** [comment]
Thanks for your contribution! I integrated it into the master in a backward-compatible way :) and kept the CI as well.

**Comment by devstein** [comment]
Amazing! Glad I could help
