### ISSUE TITLE
In what this package differs from jaytaylor/html2text?

### ISSUE THREAD

**Issue by ifraixedes** [k3a/html2text#7]
_jaytaylor/html2text_ package is mentioned in the README as an alternative to this package.

_jaytaylor/html2text_ looks more famous than this one, but I guess that there were good reasons why you created this package and not used _jaytaylor/html2text_.

Could you tell me and ultimately add those advantages and tradeoffs of using this package rather than _jaytaylor/html2text_?

Many thanks.

**Comment by k3a** [comment]
For some reason I couldn't find an existing library when I started this one (I nave no idea why!). Only after some time, I discovered more feature-full jaytaylor/html2text (which looks older though) so I mentioned it in README. 

My library works fine but offers basic functionality only and I don't expect further development (except some fixes). I will keep it for compatibility reasons.
